### ISSUE TITLE
Error when use dockerfile for cpu

### ISSUE THREAD

**Issue by HcPlu** [SUSTechGameAI/GVGAI_GYM#1]
error happened here

`File "/app/GVGAI_GYM/setup.py", line 24, in run
        java.main(path)
      File "build.py", line 20, in main
        if(shutil.which("javac")):
    AttributeError: 'module' object has no attribute 'which'`

well, I think this problem  happend as the version for python .As I known, the default python  is 2.7,but code in  build.py`if (shutil.which(javac))` is used in python >3.3.

**Comment by HawkTom** [comment]
> error happened here
> 
> `File "/app/GVGAI_GYM/setup.py", line 24, in run java.main(path) File "build.py", line 20, in main if(shutil.which("javac")): AttributeError: 'module' object has no attribute 'which'`
> 
> well, I think this problem happend as the version for python .As I known, the default python is 2.7,but code in build.py`if (shutil.which(javac))` is used in python >3.3.

I firstly install the anaconda in Docker, so the python's version in Docker should be python3.

**Comment by HcPlu** [comment]
My Anaconda version is **Anaconda2-2019.10-Linux-x86_64**,I dont why it still happed with removing all file about py2.7

**Comment by HcPlu** [comment]
Ohhh ,I see that.My Anaconda version is Anaconda2-2019.10-Linux-x86_64,that's why  I meets error.Maybe you can add tips about it as Readme does not mention about version is 2 or 3

**Comment by HawkTom** [comment]
> My Anaconda version is **Anaconda2-2019.10-Linux-x86_64**,I dont why it still happed with removing all file about py2.7

Anaconda2-2019.10-Linux-x86_64 is the Python2. 
You can download from here:  https://www.anaconda.com/distribution/
