### ISSUE TITLE
Maybe A little bug in setup.py when installing

### ISSUE THREAD

**Issue by HcPlu** [SUSTechGameAI/GVGAI_GYM#2]
when installing it.it seems setup.py do not mention about module "imageio" which inclued in GVGAI_GYM\gym_gvgai\envs\gvgai\clients\GVGAI-PythonClient\src\utils\ClientCommGYM.py.
Error happend when runing the sample code

and I make it by running "pip install imageio"  after "pip install -e ."

**Comment by HawkTom** [comment]
> when installing it.it seems setup.py do not mention about module "imageio" which inclued in GVGAI_GYM\gym_gvgai\envs\gvgai\clients\GVGAI-PythonClient\src\utils\ClientCommGYM.py.
> Error happend when runing the sample code
> 
> and I make it by running "pip install imageio" after "pip install -e ."

Thanks for your issuses.  The imageio is included in anaconda, so I didn't add the imagio in setup.py.
